feature_map_dict = {
'Zeitpunkt' : 0,
'24h-Bilanz_(Fluessigkeiten-Einfuhr_vs_-Ausfuhr)' : 1,
'AF' : 2,
'AF_spontan' : 3,
'Albumin' : 4,
'BE_arteriell' : 5,
'Bicarbonat_arteriell' : 6,
'Bilirubin_ges.' : 7,
'CK-MB' : 8,
'CK' : 9,
'Compliance' : 10,
'DAP' : 11,
'GOT' : 12,
'GPT' : 13,
'HF' : 14,
'Haematokrit' : 15,
'Haemoglobin' : 16,
'Harnstoff' : 17,
'Horowitz-Quotient_(ohne_Temp-Korrektur)' : 18,
'INR' : 19,
'Koerperkerntemperatur' : 20,
'Kreatinin' : 21,
'LDH' : 22,
'Laktat_arteriell' : 23,
'Leukozyten' : 24,
'Lipase' : 25,
'MAP' : 26,
'PCT' : 27,
'PEEP' : 28,
'P_EI' : 29,
'SAP' : 30,
'SaO2' : 31,
'SpO2' : 32,
'SzvO2' : 33,
'Thrombozyten' : 34,
'ZVD' : 35,
'individuelles_Tidalvolumen_pro_kg_idealem_Koerpergewicht' : 36,
'pH_arteriell' : 37,
'pTT' : 38,
'paCO2_(ohne_Temp-Korrektur)' : 39,
'paO2_(ohne_Temp-Korrektur)' : 40,
'SVRI' : 41,
'etCO2' : 42,
'SVI_(kontinuierlich)' : 43,
'CRP' : 44,
'HI_(kontinuierlich)' : 45,
'IL-6' : 46,
'Lagerungstherapie' : 47,
'HZV_(kontinuierlich)' : 48,
'ECMO' : 49,
'Extrakorporaler_Gasfluss_(O2)' : 50,
'MPAP' : 51,
'HI_(Bolus)' : 52,
'Lymphozyten_absolut' : 53,
'D-Dimere' : 54,
'SVI_(Bolus)' : 55,
'Gaszusammensetzung_(%O2)' : 56,
'Extrakorporaler_Blutfluss' : 57,
'BNP' : 58,
'Lymphozyten_prozentual' : 59,
'SV_(kontinuierlich)' : 60,
'NT-pro_BNP' : 61,
'DPAP' : 62,
'EVLWI' : 63,
'HZV_(Bolus)' : 64,
'Troponin' : 65,
'I:E' : 66,
'Inhalatives_NO' : 67,
'PVRI' : 68,
'FiO2' : 69,
'GEDVI' : 70,
'Amylase' : 71,
'deltaP' : 72,
'SPAP' : 73,
'FeO2' : 74,
'PCWP' : 75,
'SV_(Bolus)' : 76,
'Clonidin_intravenoes_kontinuierlich' : 77,
'Furosemid_intravenoes_kontinuierlich' : 78,
'Norepinephrin_intravenoes_kontinuierlich' : 79,
'Propofol_intravenoes_kontinuierlich' : 80,
'Sufentanil_intravenoes_kontinuierlich' : 81,
'Hydrocortison_intravenoes_bolusweise' : 82,
'Vasopressin_intravenoes_kontinuierlich' : 83,
'Rocuronium_intravenoes_bolusweise' : 84,
'Isofluran_inhalativ' : 85,
'Midazolam_intravenoes_kontinuierlich' : 86,
'Sevofluran_inhalativ' : 87,
'Morphin_intravenoes_kontinuierlich' : 88,
'Prednisolon_intravenoes_bolusweise' : 89,
'Dexamethason_intravenoes_bolusweise' : 90,
'Milrinon_intravenoes_kontinuierlich' : 91,
'Terlipressin_intravenoes_bolusweise' : 92,
'Fentanyl_intravenoes_kontinuierlich' : 93,
'Inhalatives_Iloprost' : 94,
'Dobutamin_intravenoes_kontinuierlich' : 95,
'Levosimendan_intravenoes_kontinuierlich' : 96,
'Ketanest_intravenoes_kontinuierlich' : 97,
'Fludrocortison_peroral_bolusweise' : 98,
'Epinephrin_intravenoes_kontinuierlich' : 99,
'Dexmedetomidin_intravenoes_kontinuierlich' : 100,
'CK-MB_MIMIC' : 101,
'LDH_MIMIC' : 102,
'Lipase_MIMIC' : 103,
'BNP_MIMIC' : 104,
'Tidalvolumen' : 105,
'Tidalvolumen_spont' : 106,
'Alter' : 107,
'Geschlecht' : 108,
'Gewicht' : 109,
'Groesse' : 110,
'BMI' : 111,
'Minimaler_Horowitz' : 112,
'ARDS' : 113,
'Pneumonie' : 114,
'Aspiration' : 115,
'Beinahe-Ertrinken' : 116,
'Thoraxtrauma' : 117,
'Sepsis' : 118,
'Pankreatitis' : 119,
'Fettembolie' : 120,
'TRALI' : 121,
'Verbrennungstrauma' : 122,
'Lungenoedem' : 123,
'Herzinsuffizienz' : 124,
'Hypervolaemie' : 125,
'admission_id' : 126,
'Zeitpunkt_minimaler_Horowitz' : 127
}
feature_map_dict_rev = {
0 : 'Zeitpunkt',
1 : '24h-Bilanz_(Fluessigkeiten-Einfuhr_vs_-Ausfuhr)',
2 : 'AF',
3 : 'AF_spontan',
4 : 'Albumin',
5 : 'BE_arteriell',
6 : 'Bicarbonat_arteriell',
7 : 'Bilirubin_ges.',
8 : 'CK-MB',
9 : 'CK',
10 : 'Compliance',
11 : 'DAP',
12 : 'GOT',
13 : 'GPT',
14 : 'HF',
15 : 'Haematokrit',
16 : 'Haemoglobin',
17 : 'Harnstoff',
18 : 'Horowitz-Quotient_(ohne_Temp-Korrektur)',
19 : 'INR',
20 : 'Koerperkerntemperatur',
21 : 'Kreatinin',
22 : 'LDH',
23 : 'Laktat_arteriell',
24 : 'Leukozyten',
25 : 'Lipase',
26 : 'MAP',
27 : 'PCT',
28 : 'PEEP',
29 : 'P_EI',
30 : 'SAP',
31 : 'SaO2',
32 : 'SpO2',
33 : 'SzvO2',
34 : 'Thrombozyten',
35 : 'ZVD',
36 : 'individuelles_Tidalvolumen_pro_kg_idealem_Koerpergewicht',
37 : 'pH_arteriell',
38 : 'pTT',
39 : 'paCO2_(ohne_Temp-Korrektur)',
40 : 'paO2_(ohne_Temp-Korrektur)',
41 : 'SVRI',
42 : 'etCO2',
43 : 'SVI_(kontinuierlich)',
44 : 'CRP',
45 : 'HI_(kontinuierlich)',
46 : 'IL-6',
47 : 'Lagerungstherapie',
48 : 'HZV_(kontinuierlich)',
49 : 'ECMO',
50 : 'Extrakorporaler_Gasfluss_(O2)',
51 : 'MPAP',
52 : 'HI_(Bolus)',
53 : 'Lymphozyten_absolut',
54 : 'D-Dimere',
55 : 'SVI_(Bolus)',
56 : 'Gaszusammensetzung_(%O2)',
57 : 'Extrakorporaler_Blutfluss',
58 : 'BNP',
59 : 'Lymphozyten_prozentual',
60 : 'SV_(kontinuierlich)',
61 : 'NT-pro_BNP',
62 : 'DPAP',
63 : 'EVLWI',
64 : 'HZV_(Bolus)',
65 : 'Troponin',
66 : 'I:E',
67 : 'Inhalatives_NO',
68 : 'PVRI',
69 : 'FiO2',
70 : 'GEDVI',
71 : 'Amylase',
72 : 'deltaP',
73 : 'SPAP',
74 : 'FeO2',
75 : 'PCWP',
76 : 'SV_(Bolus)',
77 : 'Clonidin_intravenoes_kontinuierlich',
78 : 'Furosemid_intravenoes_kontinuierlich',
79 : 'Norepinephrin_intravenoes_kontinuierlich',
80 : 'Propofol_intravenoes_kontinuierlich',
81 : 'Sufentanil_intravenoes_kontinuierlich',
82 : 'Hydrocortison_intravenoes_bolusweise',
83 : 'Vasopressin_intravenoes_kontinuierlich',
84 : 'Rocuronium_intravenoes_bolusweise',
85 : 'Isofluran_inhalativ',
86 : 'Midazolam_intravenoes_kontinuierlich',
87 : 'Sevofluran_inhalativ',
88 : 'Morphin_intravenoes_kontinuierlich',
89 : 'Prednisolon_intravenoes_bolusweise',
90 : 'Dexamethason_intravenoes_bolusweise',
91 : 'Milrinon_intravenoes_kontinuierlich',
92 : 'Terlipressin_intravenoes_bolusweise',
93 : 'Fentanyl_intravenoes_kontinuierlich',
94 : 'Inhalatives_Iloprost',
95 : 'Dobutamin_intravenoes_kontinuierlich',
96 : 'Levosimendan_intravenoes_kontinuierlich',
97 : 'Ketanest_intravenoes_kontinuierlich',
98 : 'Fludrocortison_peroral_bolusweise',
99 : 'Epinephrin_intravenoes_kontinuierlich',
100 : 'Dexmedetomidin_intravenoes_kontinuierlich',
101 : 'CK-MB_MIMIC',
102 : 'LDH_MIMIC',
103 : 'Lipase_MIMIC',
104 : 'BNP_MIMIC',
105 : 'Tidalvolumen',
106 : 'Tidalvolumen_spont',
107 : 'Alter',
108 : 'Geschlecht',
109 : 'Gewicht',
110 : 'Groesse',
111 : 'BMI',
112 : 'Minimaler_Horowitz',
113 : 'ARDS',
114 : 'Pneumonie',
115 : 'Aspiration',
116 : 'Beinahe-Ertrinken',
117 : 'Thoraxtrauma',
118 : 'Sepsis',
119 : 'Pankreatitis',
120 : 'Fettembolie',
121 : 'TRALI',
122 : 'Verbrennungstrauma',
123 : 'Lungenoedem',
124 : 'Herzinsuffizienz',
125 : 'Hypervolaemie',
126 : 'admission_id',
127 : 'Zeitpunkt_minimaler_Horowitz'
}
list_all_features = [
'Zeitpunkt',
'24h-Bilanz_(Fluessigkeiten-Einfuhr_vs_-Ausfuhr)',
'AF',
'AF_spontan',
'Albumin',
'BE_arteriell',
'Bicarbonat_arteriell',
'Bilirubin_ges.',
'CK-MB',
'CK',
'Compliance',
'DAP',
'GOT',
'GPT',
'HF',
'Haematokrit',
'Haemoglobin',
'Harnstoff',
'Horowitz-Quotient_(ohne_Temp-Korrektur)',
'INR',
'Koerperkerntemperatur',
'Kreatinin',
'LDH',
'Laktat_arteriell',
'Leukozyten',
'Lipase',
'MAP',
'PCT',
'PEEP',
'P_EI',
'SAP',
'SaO2',
'SpO2',
'SzvO2',
'Thrombozyten',
'ZVD',
'individuelles_Tidalvolumen_pro_kg_idealem_Koerpergewicht',
'pH_arteriell',
'pTT',
'paCO2_(ohne_Temp-Korrektur)',
'paO2_(ohne_Temp-Korrektur)',
'SVRI',
'etCO2',
'SVI_(kontinuierlich)',
'CRP',
'HI_(kontinuierlich)',
'IL-6',
'Lagerungstherapie',
'HZV_(kontinuierlich)',
'ECMO',
'Extrakorporaler_Gasfluss_(O2)',
'MPAP',
'HI_(Bolus)',
'Lymphozyten_absolut',
'D-Dimere',
'SVI_(Bolus)',
'Gaszusammensetzung_(%O2)',
'Extrakorporaler_Blutfluss',
'BNP',
'Lymphozyten_prozentual',
'SV_(kontinuierlich)',
'NT-pro_BNP',
'DPAP',
'EVLWI',
'HZV_(Bolus)',
'Troponin',
'I:E',
'Inhalatives_NO',
'PVRI',
'FiO2',
'GEDVI',
'Amylase',
'deltaP',
'SPAP',
'FeO2',
'PCWP',
'SV_(Bolus)',
'Clonidin_intravenoes_kontinuierlich',
'Furosemid_intravenoes_kontinuierlich',
'Norepinephrin_intravenoes_kontinuierlich',
'Propofol_intravenoes_kontinuierlich',
'Sufentanil_intravenoes_kontinuierlich',
'Hydrocortison_intravenoes_bolusweise',
'Vasopressin_intravenoes_kontinuierlich',
'Rocuronium_intravenoes_bolusweise',
'Isofluran_inhalativ',
'Midazolam_intravenoes_kontinuierlich',
'Sevofluran_inhalativ',
'Morphin_intravenoes_kontinuierlich',
'Prednisolon_intravenoes_bolusweise',
'Dexamethason_intravenoes_bolusweise',
'Milrinon_intravenoes_kontinuierlich',
'Terlipressin_intravenoes_bolusweise',
'Fentanyl_intravenoes_kontinuierlich',
'Inhalatives_Iloprost',
'Dobutamin_intravenoes_kontinuierlich',
'Levosimendan_intravenoes_kontinuierlich',
'Ketanest_intravenoes_kontinuierlich',
'Fludrocortison_peroral_bolusweise',
'Epinephrin_intravenoes_kontinuierlich',
'Dexmedetomidin_intravenoes_kontinuierlich',
'CK-MB_MIMIC',
'LDH_MIMIC',
'Lipase_MIMIC',
'BNP_MIMIC',
'Tidalvolumen',
'Tidalvolumen_spont',
'Alter',
'Geschlecht',
'Gewicht',
'Groesse',
'BMI',
'Minimaler_Horowitz',
'ARDS',
'Pneumonie',
'Aspiration',
'Beinahe-Ertrinken',
'Thoraxtrauma',
'Sepsis',
'Pankreatitis',
'Fettembolie',
'TRALI',
'Verbrennungstrauma',
'Lungenoedem',
'Herzinsuffizienz',
'Hypervolaemie',
'admission_id',
'Zeitpunkt_minimaler_Horowitz'
]
