# Contains an overview of attribute indice mapping
SUBJECT_ID = 0
ADMISSION_ID = 1
UNIT_STAY_INFO = 2
GENDER = 3
AGE = 4
ADMISSION_LENGTH = 5
DIAGNOSIS = 6
HEIGHT = 7
WEIGHT = 8
MECHVENTSTART = 9
MECHVENTEND = 10
MECHVENTDURATION = 11